CREATE USER IF NOT EXISTS 'zoomzoomi'@'%' IDENTIFIED BY 'zoom123';
CREATE DATABASE IF NOT EXISTS travel DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS travel_test DEFAULT CHARACTER SET utf8mb4;
GRANT ALL PRIVILEGES ON *.* TO 'zoomzoomi'@'%';
FLUSH PRIVILEGES;