CREATE USER IF NOT EXISTS 'zoomzoomi'@'%' IDENTIFIED BY 'zoom123';
GRANT ALL PRIVILEGES ON *.* TO 'zoomzoomi'@'%' WITH GRANT OPTION;
CREATE DATABASE IF NOT EXISTS travel DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS travel_test DEFAULT CHARACTER SET utf8mb4;
FLUSH PRIVILEGES;